# nonk8s
apiVersion: "backstage.io/v1alpha1"
kind: "Component"
metadata:
  name: "tjenestedokumentasjon"
  tags: []
spec:
  type: "experiment"
  lifecycle: "experimental"
  owner: "datadeling_og_distribusjon"
  system: "tjenester"
